import AnimatedText from '@/components/AnimatedText';
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import developing from "../../public/images/profile/developing.png";
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import developer1 from "../../public/images/profile/developer1.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-[480px] ml-4'>
              <Image 
                src={developer1}
                alt="EG"
                className='w-full h-auto'
                priority
                sizes='(max-width: 768px) 100vw,
                (max-width: 1200px) 50vh,
                33vw'
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText 
                text="Turning Vision Into Reality With Code And Design."
                className='!text-6xl !text-left'
              />
              <p className='my-4 text-base font-medium'>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link 
                  href="/CV_EMANUEL_GARCIA-.pdf"
                  target={"_blank"}
                  className="
                    flex items-center bg-dark 
                    text-light p-2.5 px-6 hover:bg-light dark:bg-light
                    rounded-lg text-lg font-semibold hover:text-dark dark:text-dark
                    border-2 border-solid border-transparent hover:border-dark
                    hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                  "
                  download={true}
                >
                  Resume
                  <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                <Link 
                  href="mailto:mr.emanuel.garcia93@gmail.com" 
                  target={"_blank"}
                  className="
                    ml-4 text-lg font-medium capitalize
                    text-dark underline dark:text-light
                  "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24'>
          <Image
            src={lightBulb}
            alt="EG"
            className='w-full h-auto'
          />
        </div>
      </main>
    </>
  )
}
